### ISSUE TITLE
. . .

### ISSUE THREAD

**Issue by Arthur-The-Ok** [3Snake3/Units-mod#1]
Just reloaded the game and this is the first thing that pops up:

An error has ocurred

Errors have ocurred loading content

units-mod:

discharge:
File: discharge.hjson

[Serialization] Serialization trace:
{}.item
item (type.ItemStack)
[IllegalArgument] "item": no item found with name 'creostone'.
Make sure 'creostone' is spelled correctly, and that it really exists!
This also may occur because its file faild to parse.

tower:
File: tower.hjson

[Serialization] Serialization trace:
{}.item
item (type.ItemStack)
[IllegalArgument] "item": no item found with name 'creostone'.
Make sure 'creostone' is spelled correctly, and that it really exists!
This also may occur because its file faild to parse.

galaxy:
File: galaxy.hjson

[Serialization] Serialization trace:
{}.item
item (type.ItemStack)
[IllegalArgument] "item": no item found with name 'creostone'.
Make sure 'creostone' is spelled correctly, and that it really exists!
This also may occur because its file faild to parse.

twilight:
File: twilight.hjson

[Serialization] Serialization trace:
{}.item
item (type.ItemStack)
[IllegalArgument] "item": no item found with name 'creostone'.
Make sure 'creostone' is spelled correctly, and that it really exists!
This also may occur because its file faild to parse.

blaster:
File: blaster.hjson

[Serialization] Serialization trace:
{}.item
item (type.ItemStack)
[IllegalArgument] "item": no item found with name 'creostone'.
Make sure 'creostone' is spelled correctly, and that it really exists!
This also may occur because its file faild to parse.

power:
File: power.hjson

[IllegalArgument] Content 'tower' isn't in the tech tree, but 'units-mod-power' requires it to be researched.

tesla:
File: tesla.hjson

[Serialization] Serialization trace:
{}.item
item (type.ItemStack)
[IllegalArgument] "item": no item found with name 'creostone'.
Make sure 'creostone' is spelled correctly, and that it really exists!
This also may occur because its file faild to parse.

**Comment by 3Snake3** [comment]
I already fixed it. Enjoy the game.
