### ISSUE TITLE
Content errors

### ISSUE THREAD

**Issue by LoxStorm** [3Snake3/Units-mod#3]
Can't play campaign

![Screenshot_20210908_182856_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132493849-d4b4761e-6d1a-47c1-9213-14e944a1ac9c.jpg)

![Screenshot_20210908_182851_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132493864-717971c5-4e4e-48a0-99a7-c01eb6099f93.jpg)

![Screenshot_20210908_182847_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132493914-9e9b9691-0867-4847-ba30-b5150b479237.jpg)

![Screenshot_20210908_182842_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132493948-e31960c9-3353-4d01-b5dc-c9d0e9cc9ae2.jpg)

![Screenshot_20210908_182838_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132494284-6895e3de-ddd7-443c-85a0-0fe08ec780d0.jpg)

![Screenshot_20210908_182833_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132494320-0cf3c54a-acfe-4144-8be4-3f4eb74a7095.jpg)

![Screenshot_20210908_182821_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132494381-a200a7d6-c087-4d32-9fd5-c94a8b8187b5.jpg)

![Screenshot_20210908_182812_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132494464-72ceedfd-3a9c-44bc-9c73-e7a36900bd3f.jpg)

![Screenshot_20210908_182807_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132494489-d350af42-a734-4cab-96a5-b88b3854769f.jpg)

![Screenshot_20210908_182803_io anuke mindustry](https://user-images.githubusercontent.com/90319073/132494524-83850521-808a-4091-8856-0c3abe944c16.jpg)

Happen after i installed the new update

**Comment by 3Snake3** [comment]
@LoxStorm 
The mod is no longer supported on builds below 127.

**Comment by LoxStorm** [comment]
> @LoxStorm
> The mod is no longer supported on builds below 127.

Ouh, okay. Is there a way for me to download the old version?

**Comment by LoxStorm** [comment]
Ouh, okay. Is there a way for me to download the old version?

**Comment by 3Snake3** [comment]
@LoxStorm 
I can create a new repository for 6.0 builds. But perhaps it will be archived and unlikely to be updated.

**Comment by LoxStorm** [comment]
> @LoxStorm I can create a new repository for 6.0 builds. But perhaps it will be archived and unlikely to be updated.

Ouh okay, and where can i fine it?
I really enjoy the new unit that you added to the game, it is very fun to do.

**Comment by 3Snake3** [comment]
@LoxStorm 
Now you can find the mod for v6 by the link.
And if you wish to update the game to v7, install the mod from the mod browser.

3Snake3/Units-mod-v6

**Comment by LoxStorm** [comment]
> @LoxStorm Now you can find the mod for v6 by the link. And if you wish to update the game to v7, install the mod from the mod browser.
> 
> 3Snake3/Units-mod-v6

Tq soo much, the mod is working just fine now
